export const PRODUCTS = {
    CONTAIN: "PRODUCTS_CONTAIN",
    ADD: "PRODUCTS_ADD",
    EDIT: "PRODUCTS_EDIT",
    REMOVE: "PRODUCTS_REMOVE"
}

export const CART = {
    CONTAIN: "CART_CONTAIN",
    ADD: "CART_ADD",
    REMOVE: "CART_REMOVE",
    CLEAR: "CART_CLEAR"
}